[package]
name = "cabot"
version = "0.1.0"
authors = ["Guillaume Gauvrit <guillaume@gauvr.it>"]
readme = "README.md"
keywords = ["http", "https", "request", "client"]
categories = ["web-programming::http-client", "command-line-interface"]
description = """Simple HTTP Client."""
license = "BSD-3-Clause"
documentation = "https://docs.rs/crate/cabot"
#homepage = "https://github.com/mardiros/cabot"
repository = "https://github.com/mardiros/cabot"


[lib]
name = "cabot"
path = "src/lib.rs"


[[bin]]
name = "cabot"
path = "src/bin.rs"
doc = false

[dependencies]

clap = "^2.24.2"
log = "^0.3.8"
pretty_env_logger = "^0.1.0"

rustls = "^0.8.0"
webpki-roots = "^0.10.0"
url = "^1.4.1"
